### ISSUE TITLE
Figure captions from plots?

### ISSUE THREAD

**Issue by ejolly** [kiwi0fruit/knitty#18]
I can't seem to find an example where a figure caption is added to a plot generated via python rather than an image loaded using markdown. For example, how do you add a figure caption to a plot generated using the code below (snippet from stitch examples) when converting a `.md` or `.pymd` file to `.pdf`? The resulting pdf has a caption "Figure 1: " but it's unclear how to add a figure caption to this

```
{python, sinus, echo=False}
# As this all produces no output, it should go into the same input section...
import numpy as np
import matplotlib.pyplot as plt
y = np.linspace(2, 10)
line, = plt.plot(y, np.sin(y))
```

**Comment by kiwi0fruit** [comment]
For this I use [matplotlibhelper](https://github.com/kiwi0fruit/matplotlibhelper#usage-example) (there are more comments there). Markdown code block:

````python
@{echo=False}
```python
import numpy as np
import IPython.display as ds
import matplotlibhelper as mh
mh.ready(font_size=14, ext='png')  # should be run before import matplotlib.pyplot
import matplotlib.pyplot as plt

def markdown(*args, **kwargs): return ds.display(ds.Markdown(*args, **kwargs))

plt.figure(figsize=mh.figsize(w=6))
y = np.linspace(2, 10)
plt.plot(y, np.sin(y))
markdown(f'![My beautiful figure]({mh.img(plt)}){{#fig:1}}')
```
````
or in Python:

````python
# %% {echo=False}
import numpy as np
import IPython.display as ds
import matplotlibhelper as mh
mh.ready(font_size=14, ext='png')  # should be run before import matplotlib.pyplot
import matplotlib.pyplot as plt

def markdown(*args, **kwargs): return ds.display(ds.Markdown(*args, **kwargs))

plt.figure(figsize=mh.figsize(w=6))
y = np.linspace(2, 10)
plt.plot(y, np.sin(y))
markdown(f'![My beautiful figure]({mh.img(plt)}){{#fig:1}}')
````

**Comment by kiwi0fruit** [comment]
At the moment general case solution is not available. The working way is to get somehow an image string for `Markdown(...)`. Though for static documents (\*.pdf, \*.md, \*.docx) matplotlib plots is enough for most cases. And if you need to export to *.ipynb you can always do something like plotting image without caption in the first code cell (knitty grabs image OK) then add a caption in the next code cell.
